// Hungarian copy is PROPOSAL until Áron approves.
export const A = {
  launcher: "Asszisztens",
  dialog: "Asszisztens",
  close: "Bezárás",
  general: "Általános kérdés",
  loading: "Betöltés...",
  notConfigured: "Az asszisztens még nincs beállítva (Groq kulcs hiányzik). A jegyzetek és a Mi vár rám? működnek.",
  tabAsk: "Kérdés",
  tabNote: "Jegyzet",
  tabTicket: "Hibajegy",
  quick: "Mire való ez?",
  askPlaceholder: "Írja le a kérdését",
  send: "Küldés",
  thinking: "Gondolkodom...",
  counter: (n: number, max: number) => `${n} / ${max} üzenet`,
  limitHint: "Elérte az üzenetkorlátot. Kezdjen új beszélgetést.",
  reset: "Új beszélgetés",
  you: "Ön",
  assistant: "Asszisztens",
  noteNeedItem: "Jegyzet írásához nyisson meg egy tartalmat.",
  notePlaceholder: "Jegyzet a tartalomhoz",
  noteSave: "Mentés",
  noteEmpty: "Még nincs jegyzet.",
  ticketPrompt: "Mi a gond, vagy mit kér?",
  ticketDraft: "Vázlat",
  ticketTitle: "Cím",
  ticketBody: "Leírás",
  ticketLabel: "Típus",
  ticketRepo: "Tárhely",
  labelBug: "Hiba",
  labelBacklog: "Ötlet / kérés",
  ticketFile: "Beküldöm",
  ticketDone: "Létrehozva",
  ticketFallback: "Nem tudtam közvetlenül létrehozni. Nyissa meg itt, a mezők ki vannak töltve:",
  ticketOpen: "Megnyitás",
  askAbout: "Kérdezek róla",
  tabActions: "Teendők",
  whatsWaiting: "Mi vár rám?",
  nothingWaiting: "Jelenleg nem vár Önre semmi.",
  waitingItems: "Az Ön döntésére váró anyagok",
  waitingDecisions: "Nyitott döntések",
  daysAgo: (n: number) => `${n} napja`,
  actionPrompt: "Mit tegyek?",
  actionPropose: "Javaslat",
  confirm: "Megerősítem",
  cancel: "Mégse",
  open: "Megnyitás",
  fVerdict: "Döntés",
  fComment: "Megjegyzés",
  fReason: "Ok",
  fAnswer: "Válasz",
  fQuestion: "Kérdés",
  fContext: "Háttér",
  fOptions: "Lehetőségek",
  fRecommendation: "Javaslat",
  fDeadline: "Határidő",
  fDecidedBy: "Kitől",
  fBody: "Szöveg",
  fTitle: "Cím",
  fLabel: "Típus",
  forWhom: { aron: "Áron", peter: "Péter", either: "bárki" } as Record<string, string>,
  genericError: "Valami elromlott. Kérjük, próbálja újra.",
} as const;
