// Hungarian copy is PROPOSAL until Áron approves.
export const A = {
  launcher: "Asszisztens",
  dialog: "Asszisztens",
  close: "Bezárás",
  general: "Általános kérdés",
  loading: "Betöltés...",
  notConfigured: "Az asszisztens még nincs beállítva. A jegyzetek működnek.",
  tabAsk: "Kérdés",
  tabNote: "Jegyzet",
  tabTicket: "Hibajegy",
  quick: "Mire való ez?",
  askPlaceholder: "Írja le a kérdését",
  send: "Küldés",
  thinking: "Gondolkodom...",
  counter: (n: number, max: number) => `${n} / ${max} üzenet`,
  limitHint: "Elérte az üzenetkorlátot. Kezdjen új beszélgetést.",
  reset: "Új beszélgetés",
  you: "Ön",
  assistant: "Asszisztens",
  noteNeedItem: "Jegyzet írásához nyisson meg egy tartalmat.",
  notePlaceholder: "Jegyzet a tartalomhoz",
  noteSave: "Mentés",
  noteEmpty: "Még nincs jegyzet.",
  ticketPrompt: "Mi a gond, vagy mit kér?",
  ticketDraft: "Vázlat",
  ticketTitle: "Cím",
  ticketBody: "Leírás",
  ticketLabel: "Típus",
  ticketRepo: "Tárhely",
  labelBug: "Hiba",
  labelBacklog: "Ötlet / kérés",
  ticketFile: "Beküldöm",
  ticketDone: "Létrehozva",
  ticketFallback: "Nem tudtam közvetlenül létrehozni. Nyissa meg itt, a mezők ki vannak töltve:",
  ticketOpen: "Megnyitás",
  askAbout: "Kérdezek róla",
  genericError: "Valami elromlott. Kérjük, próbálja újra.",
} as const;
