// Hungarian copy is PROPOSAL until Áron approves.
export const A = {
  launcher: "Asszisztens",
  dialog: "Asszisztens",
  close: "Bezárás",
  tabChat: "Beszélgetés",
  tabNotes: "Jegyzetek",
  newChat: "Új beszélgetés",
  del: "Törlés",
  delConfirm: "Biztosan törli ezt a beszélgetést?",
  previous: "Korábbi beszélgetések",
  noPrevious: "Még nincs korábbi beszélgetés.",
  untitled: "Névtelen beszélgetés",
  inputPlaceholder: "Írja le a kérdését vagy kérését",
  quickWaiting: "Mi vár rám?",
  quickDrafts: "Mi van a vázlatokban?",
  quickAbilities: "Mit tudsz?",
  chipTicket: "Készíts jegyet erről",
  pendingBadge: (n: number) => `${n} Önre váró anyag`,
  suggestions: "Javaslatok",
  execute: "Végrehajtom",
  executing: "Végrehajtom...",
  dismiss: "Mégse",
  executed: "Végrehajtva",
  newState: "Új állapot",
  fItem: "Anyag",
  fPath: "Oldal",
  askAbout: "Kérdezek róla",
  loading: "Betöltés...",
  notConfigured: "Az asszisztens még nincs beállítva (Groq kulcs hiányzik). A jegyzetek és a Mi vár rám? működnek.",
  send: "Küldés",
  thinking: "Gondolkodom...",
  noteNeedItem: "Jegyzet írásához nyisson meg egy tartalmat.",
  notePlaceholder: "Jegyzet a tartalomhoz",
  noteSave: "Mentés",
  noteEmpty: "Még nincs jegyzet.",
  labelBug: "Hiba",
  labelBacklog: "Ötlet / kérés",
  whatsWaiting: "Mi vár rám?",
  nothingWaiting: "Jelenleg nem vár Önre semmi.",
  waitingItems: "Az Ön döntésére váró anyagok",
  waitingDecisions: "Nyitott döntések",
  daysAgo: (n: number) => `${n} napja`,
  cancel: "Mégse",
  open: "Megnyitás",
  fVerdict: "Döntés",
  fComment: "Megjegyzés",
  fReason: "Ok",
  fAnswer: "Válasz",
  fQuestion: "Kérdés",
  fContext: "Háttér",
  fOptions: "Lehetőségek",
  fRecommendation: "Javaslat",
  fDeadline: "Határidő",
  fDecidedBy: "Kitől",
  fBody: "Szöveg",
  fTitle: "Cím",
  fLabel: "Típus",
  forWhom: { aron: "Áron", peter: "Péter", either: "bárki" } as Record<string, string>,
  genericError: "Valami elromlott. Kérjük, próbálja újra.",
} as const;
