import type { ContentCategory, Verdict } from "./types";

// ⚠️ HU PROPOSALS (translating-english-to-hungarian pass) — not signed off by Áron.
// Status labels live in lib/marketing/types.ts (STATUS_LABELS).

export const CATEGORY_LABEL: Record<ContentCategory, string> = {
  script: "Szkript",
  email: "E-mail",
  ad: "Hirdetés",
  lead_magnet: "Lead magnet",
  landing: "Landing oldal",
  video: "Videó",
  image: "Kép",
  other: "Egyéb",
};

export const VERDICT_LABEL: Record<Verdict, string> = {
  approve: "Jóváhagyta",
  changes: "Javítást kért",
  rewrite: "Újraírást kért",
};

/** The three buttons (spec §4). */
export const VERDICT_ACTION: Record<Verdict, string> = {
  approve: "Jóváhagyom",
  changes: "Javítást kérek",
  rewrite: "Írja újra",
};

export const AUTHOR_LABEL: Record<string, string> = {
  ai: "AI",
  user: "Kézi szerkesztés",
  import: "Importált",
};

export const UI = {
  inboxTitle: "Anyagok",
  mine: "Rád vár",
  otherReviewer: "A másik bírálóra vár",
  aiWorking: "Az AI dolgozik rajta",
  changesRequested: "Javításra vagy újraírásra vár",
  live: "Élő",
  library: "Élő anyagok",
  nothingForYou: "Nincs mit bírálnod.",
  notReviewer: "Nem vagy bíráló, ezért csak olvashatod.",
  noReviewers: "Nincsenek bírálók beállítva, így semmi sem kerülhet élesbe.",
  waitingDays: (n: number) => `${n} napja vár`,
  version: (n: number) => `${n}. verzió`,
  notYetReviewed: "Még nem bírálta",
  edit: "Szerkesztés",
  saveAsVersion: "Mentés új verzióként",
  resetWarning: "Mentéskor mindkét jóváhagyás elvész, és az anyag újra bírálatra kerül.",
  cancel: "Mégse",
  commentLabel: "Mi legyen másképp?",
  commentRequired: "Írd le röviden, mit kell változtatni.",
  changeNote: "Mit változtattál? (nem kötelező)",
  versions: "Verziók",
  showDiff: "Eltérések az előző verzióhoz",
  hideDiff: "Eltérések elrejtése",
  comments: "Megjegyzések",
  files: "Fájlok",
  addFile: "Fájl hozzáadása",
  addLink: "Link hozzáadása",
  removeFile: "Eltávolítás",
  copyText: "Szöveg másolása",
  copied: "Másolva",
  download: "Letöltés",
  archive: "Archiválás",
  aiBusy: "Az AI éppen átírja ezt az anyagot. Ha most szerkeszted, a te változatod marad meg.",
  needsHumanAsset: "Ehhez az anyaghoz emberi munka kell (kép vagy videó).",
  liveServes: (n: number) => `Élesben a(z) ${n}. verzió van használatban`,
  reviewers: "Bírálók",
  saveReviewers: "Bírálók mentése",
  category: "Kategória",
  campaign: "Kampány",
  format: "Formátum",
  status: "Állapot",
  all: "Összes",
  pipeline: ["Vázlat", "Jóváhagyás", "Élő", "Kampányban használva"],
  publishedLink: "Megjelenés linkje",
  noLiveMatch: "Nincs élő anyag ezekkel a szűrőkkel.",
  // §6c — board/list, bulk actions, ⚠ checklist. ⚠ HU PROPOSALS.
  boardView: "Tábla",
  listView: "Lista",
  onlyMine: "Csak ami rám vár",
  columnDraft: "Vázlat",
  columnInReview: "Bírálatra vár",
  columnChanges: "Javítás kell",
  columnAiWorking: "AI írja",
  columnLive: "Élő",
  columnInCampaign: "Kampányban",
  emptyColumn: "Nincs ilyen anyag.",
  dragNotAllowed: "Ide nem lehet áthúzni: élesbe csak két jóváhagyás visz.",
  selectAll: "Mind kijelölése",
  selectedCount: (n: number) => `${n} kijelölve`,
  clearSelection: "Kijelölés törlése",
  archiveSelected: "Archiválás",
  deleteSelected: "Végleges törlés",
  deleteConfirm: (n: number) => `Végleg törlöd? ${n} anyag és a hozzá feltöltött fájlok is törlődnek. Ezt nem lehet visszavonni.`,
  deleteBlocked: "Volt már élő, ezért csak archiválható.",
  undo: "Visszavonás",
  archivedToast: (n: number) => `${n} anyag archiválva`,
  deletedToast: (n: number) => `${n} anyag törölve`,
  restoredToast: (n: number) => `${n} anyag visszaállítva`,
  restore: "Visszaállítás",
  // ⚠ checklist
  checks: "Tisztázandó kérdések",
  checksOpen: (n: number) => `${n} nyitott kérdés`,
  checkBlocksLive: "Nyitott kérdés van, ezért nem mehet élesbe. Válaszolj rá, vagy tedd félre indoklással.",
  checkStateOpen: "Nyitott",
  checkStateResolved: "Megválaszolva",
  checkStateWaived: "Félretéve",
  checkResolve: "Megválaszolom",
  checkWaive: "Félreteszem",
  checkReopen: "Újra megnyitom",
  checkAnswer: "A válasz",
  checkWaiveReason: "Miért nem kell ez?",
  checkAdd: "Új kérdés",
  checkAddPlaceholder: "Mit kell tisztázni?",
  checkFor: "Kinek szól",
  checkForAron: "Áron",
  checkForPeter: "Péter",
  checkForEither: "Bármelyik",
  checkAskedBy: "Forrás: import",
  pagePrev: "Előző",
  pageNext: "Következő",
  pageLabel: (n: number) => `${n}. oldal`,
};
